# Generated by Django 3.1 on 2021-12-29 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address_line_1', models.CharField(blank=True, max_length=50, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=50, null=True)),
                ('village', models.CharField(max_length=50)),
                ('local_gov_area', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=12, null=True)),
                ('country', models.CharField(max_length=50)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/voters')),
                ('is_registered', models.BooleanField(default=False)),
                ('is_eligible', models.BooleanField(default=False)),
                ('willing_to_register', models.BooleanField(default=False)),
                ('political_party', models.CharField(choices=[('0', 'Select your political party'), ('Accord', 'Accord'), ('Action Alliance', 'Action Alliance'), ('Action Democratic Party', 'Action Democratic Party'), ('Action Peoples Party', 'Action Peoples Party'), ('African Action Congress', 'African Action Congress'), ('African Democratic Congress', 'African Democratic Congress'), ('All Progressives Congress', 'All Progressives Congress'), ('All Progressives Grand Alliance', 'All Progressives Grand Alliance'), ('Allied Peoples Movement', 'Allied Peoples Movement'), ('Boot Party', 'Boot Party'), ('Labour Party', 'Labour Party'), ('National Rescue Movement', 'National Rescue Movement'), ('New Nigeria Peoples Party', 'New Nigeria Peoples Partys'), ('Peoples Democratic Party', 'Peoples Democratic Party'), ('Peoples Redemption Party', 'Peoples Redemption Party'), ('Social Democratic Party', 'Social Democratic Party'), ('Young Progressive Party', 'Young Progressive Party'), ('Zenith Labour Party', 'Zenith Labour Party'), ('others', 'Others')], default=0, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('0', 'Select How you heard about us'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Google', 'Google'), ('word of mouth', 'Word of Mouth'), ('youtube', 'Youtube'), ('Ads', 'Ads'), ('others', 'Others')], default=0, max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
