# Generated by Django 3.1 on 2021-12-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='gender',
            field=models.CharField(choices=[('0', 'Select Gender'), ('Female', 'Female'), ('Male', 'Male')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='voter',
            name='channel',
            field=models.CharField(choices=[('0', 'Select How you heard about us'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Google', 'Google'), ('word of mouth', 'Word of Mouth'), ('youtube', 'Youtube'), ('Ads', 'Ads'), ('others', 'Others')], default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='voter',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='phone',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='political_party',
            field=models.CharField(choices=[('0', 'Select your political party'), ('Accord', 'Accord'), ('Action Alliance', 'Action Alliance'), ('Action Democratic Party', 'Action Democratic Party'), ('Action Peoples Party', 'Action Peoples Party'), ('African Action Congress', 'African Action Congress'), ('African Democratic Congress', 'African Democratic Congress'), ('All Progressives Congress', 'All Progressives Congress'), ('All Progressives Grand Alliance', 'All Progressives Grand Alliance'), ('Allied Peoples Movement', 'Allied Peoples Movement'), ('Boot Party', 'Boot Party'), ('Labour Party', 'Labour Party'), ('National Rescue Movement', 'National Rescue Movement'), ('New Nigeria Peoples Party', 'New Nigeria Peoples Partys'), ('Peoples Democratic Party', 'Peoples Democratic Party'), ('Peoples Redemption Party', 'Peoples Redemption Party'), ('Social Democratic Party', 'Social Democratic Party'), ('Young Progressive Party', 'Young Progressive Party'), ('Zenith Labour Party', 'Zenith Labour Party'), ('others', 'Others')], default='0', max_length=100),
        ),
    ]
