# Generated by Django 3.1 on 2021-12-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_auto_20211231_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('0', 'Select Gender')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='voter',
            name='is_registered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='willing_to_register',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
