# Generated by Django 3.1 on 2021-12-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0003_auto_20211231_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='gender',
            field=models.CharField(choices=[('0', 'Select Gender'), ('Female', 'Female'), ('Male', 'Male')], default='0', max_length=10),
        ),
    ]
