# Generated by Django 3.1 on 2021-12-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0004_auto_20211231_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('0', 'Select Gender'), ('Male', 'Male')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='voter',
            name='willing_to_register',
            field=models.BooleanField(default=False),
        ),
    ]
