# Generated by Django 3.1 on 2022-01-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0005_auto_20211231_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
