# Generated by Django 3.1 on 2022-01-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0006_auto_20220116_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='gender',
            field=models.CharField(choices=[('0', 'Select Gender'), ('Female', 'Female'), ('Male', 'Male')], default='0', max_length=10),
        ),
    ]
