# Generated by Django 3.1 on 2022-01-19 02:45

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('voter', '0007_auto_20220117_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='local_gov_area',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', default=None, on_delete=django.db.models.deletion.CASCADE, to='location.localgovarea'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.state'),
        ),
    ]
