# Generated by Django 3.1 on 2021-12-29 17:41

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=50, unique=True)),
                ('activity_description', models.TextField(blank=True, max_length=500)),
                ('activity_video', models.CharField(max_length=50)),
                ('activity_date', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='photos/activity')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('program_description', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to='photos/programs')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('project_description', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to='photos/programs')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('project_objective', models.TextField(blank=True, max_length=1000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('program', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='company', chained_model_field='company', default=None, on_delete=django.db.models.deletion.CASCADE, to='program.program')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=50, null=True)),
                ('image_description', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='photos/ActivityImage')),
                ('activity', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='project', chained_model_field='project', default=None, on_delete=django.db.models.deletion.CASCADE, to='program.activity')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('program', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='company', chained_model_field='company', default=None, on_delete=django.db.models.deletion.CASCADE, to='program.program')),
                ('project', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='program', chained_model_field='program', default=None, on_delete=django.db.models.deletion.CASCADE, to='program.project')),
            ],
            options={
                'verbose_name': 'ActivityImages',
                'verbose_name_plural': 'Activity Images',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='program',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='company', chained_model_field='company', default=None, on_delete=django.db.models.deletion.CASCADE, to='program.program'),
        ),
        migrations.AddField(
            model_name='activity',
            name='project',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='program', chained_model_field='program', default=None, on_delete=django.db.models.deletion.CASCADE, to='program.project'),
        ),
    ]
