# Generated by Django 3.1 on 2021-12-29 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('company_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('channel', models.CharField(choices=[(0, 'Select How you heard about us'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Google', 'Google'), ('word of mouth', 'Word of Mouth'), ('youtube', 'Youtube'), ('Ads', 'Ads'), ('others', 'Others')], default=0, max_length=100)),
                ('involvement', models.CharField(choices=[(0, 'Select how you would get involed'), ('partner', 'partner'), ('Volunteer', 'Volunteer'), ('others', 'Others')], default=0, max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
            ],
        ),
    ]
