# Generated by Django 3.1 on 2022-01-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='involvement',
            field=models.CharField(choices=[(0, 'Select how you would get involed'), ('partner', 'Partner'), ('volunteer', 'Volunteer'), ('employment', 'Employment'), ('others', 'Others')], default=0, max_length=100),
        ),
    ]
