# Generated by Django 3.1 on 2021-12-29 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=50)),
                ('article_subtitle', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photos/article')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_url', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='photos/authors')),
                ('created_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_title', models.CharField(max_length=50)),
                ('paragraph_content', models.TextField(max_length=2500)),
                ('paragraph_image', models.ImageField(blank=True, null=True, upload_to='photos/paragraph')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='article_author',
            field=models.ManyToManyField(to='blog.Author'),
        ),
    ]
